routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/how', function (){
    return view('how');
});

Route::get('/faq', function (){
    return view('faq');
});

Route::get('/videos', 'VideoController@index');

Route::get('logout', 'Auth\LoginController@logout');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/teller', 'TellerController@store')->name('teller');
Route::get('/profile', 'ProfileController@create')->name('profile');
Route::post('/profile', 'ProfileController@store')->name('profile');


/**
 * backpack configs
 */

Route::group(['middleware' => ['web'], 'prefix' => config('backpack.base.route_prefix', ['namespace' => 'Backpack\Base\app\Http\Controllers'])], function () {
    Route::auth();
    Route::get('logout', 'Auth\LoginController@logout');
    Route::get('dashboard', 'AdminController@dashboard');
    Route::get('/', 'AdminController@redirect'); //redirects to admin dashboard
});

/**
 * backpack configs
 */
Route::group(['prefix' => config('backpack.base.route_prefix', 'admin')], function () {
    CRUD::resource('receipt', 'Admin\ReceiptCrudController');
    Route::get('receipt/{id}', function() {

    })->name('receipt.view');
    CRUD::resource('message', 'Admin\MessageCrudController');
    CRUD::resource('video', 'Admin\VideoCrudController');
    CRUD::resource('member', 'Admin\UserCrudController');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Receipt.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;

class Receipt extends Model
{
    use CrudTrait;

    protected $fillable = ['user_id', 'upload', 'confirm'];


    public function user()
    {
        return $this->belongsTo('App\User');//->withTrashed();
    }

    public function getNameAttribute()
    {
        return $this->user->name;
    }

    public function getConfirmedAttribute()
    {
        return $this->confirm ? "Confirmed" : "Pending";
    }

    public function getAdminReceiptWithLink()
    {
        if($this->upload)
            return  '<a href="'. route('receipt.view', ['id'=>$this->id]) .'" target="_blank">View Receipt</a>';

        return 'No Upload Yet';
    }
}

resources/views/dashboard.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="container">
        <div class="col-md-8">
            <div class="row">
                <div class="">
                    <div class="panel panel-default">
                        <div class="panel-heading">Dashboard</div>

                        <div class="panel-body">
                            <p>Welcome to Glochis Platform</p>
                            <br>
                            @if($user->payment == false)
                                <div class="col-md-6">
                                    @if(is_null($receipt))
                                        <p>Already Made Payment?</p>
                                        <div class="row col-md-12">
                                            <form class="form-horizontal" action="{{ route('teller') }}" method="POST" enctype="multipart/form-data">
                                                {{ csrf_field() }}
                                                <div class="form-group">
                                                    <div class="col-md-6">
                                                        <input name="receipt" type="file" class="form-control" />
                                                    </div>
                                                    <div class="col-md-2">
                                                        <button class="btn btn-success" type="submit">Upload</button>
                                                    </div>
                                                    <div class="col-md-12 alert">
                                                        @if ($errors->has('receipt'))
                                                            <span class="help-block">
                                                <strong>{{ $errors->first('receipt') }}</strong>
                                            </span>
                                                        @endif
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    @endif
                                    @if (Session::has('r-upload'))
                                        <div class="col-md-12 alert alert-success">
                                            <strong>{{ session('r-upload') }}</strong>
                                        </div>
                                    @endif
                                </div>

                                @if(is_null(auth()->user()->receipt()->first()))
                                    <div class="col-md-6">
                                        <h4>Payment Details</h4>
                                        <p>XYZ BANK</p>
                                    </div>
                                @endif


                            @elseif(isset($upline))
                                <p>Upline: {{$upline->name}}</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="">
                    <div class="panel panel-default">
                        <div class="panel-heading">Teller</div>

                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <tr>
                                        <th class="text-center">ID</th>
                                        <th class="text-center">Confirmed</th>
                                        <th class="text-center">Date Added</th>
                                        <th></th>
                                    </tr>
                                    <tbody>
                                    @if(!is_null($receipt))
                                        <tr class="text-center">
                                            <td>{{ $receipt->id }}</td>
                                            {{--                                <td>{{ $receipt->upload }}</td>--}}
                                            <td>{!! $receipt->confirmed ? '<span class="label label-success">Yes</span>' : '<span class="label label-danger">No</span>' !!}</td>
                                            <td>{{ $receipt->created_at->diffForHumans() }}</td>
                                            <td></td>
                                        </tr>
                                    @else
                                        <tr>
                                            <td class="text-warning">No upload found.</td>
                                        </tr>
                                    @endif
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>create+mess
        </div>

        <div class="col-md-4 ">
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">News</div>

                    <div class="panel-body">
                        @foreach($messages as $message)
                            <div>
                                <strong><p>{{$message->title}}</p></strong>
                                <p>{{$message->body}}</p>
                            </div>
                        @endforeach
                    </div>

                </div>
            </div>
        </div>
    </div>

    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/faq.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>FAQ - Frequently Asked Questions | Glochis Club | A Glochis African Development Initiative | Empowering our youth</title>

    <!-- SEO CONFIG -->
        @include ('includes/seo')
    <!-- SEO CONFIG -->

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="js/font-awesome-4.7.0/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link href="js/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- <link href="assets/css/now-ui-kit.css" rel="stylesheet" /> -->
    <link href="css/glochis.css" rel="stylesheet" />


</head>


<body>


    <!-- NAVIGATION -->
    @include ('includes/navigation')
    <!-- NAVIGATION -->



    <!-- PAGE CONTENT -->
    <center>
    <div class="" style="min-height:600px;">

        <div class="OtherPagesTop"></div>
        
        
        

        <!-- **************************** FAQ SECTION **************************** -->
        <div class="row container">
            <div class="col-md-12 Text-to-left">
            <br>
            <h3><strong>Frequently Asked Questions - FAQs</strong></h3>
            <hr />

                <div id="accordion" class="panel-group">

                    <!-- ACCORDION ITEM -->
                    <div class="panel panel-success">
                    <!--  // HEADER -->
                    <div class="panel-heading">
                    <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">1. Who is eligible to join the Glochis club </a>
                    </h4>
                    </div>
                    <!--  // CONTENT -->
                    <div id="collapseOne" class="panel-collapse collapse in">
                    <div class="panel-body">
                    <hr>
                    <p>Any body from the ages of 9years to 40years, who is resident in Nigeria is eligible to join Glochis club.</p>
                    </div>
                    </div>
                    </div>
                    <!-- ACCORDION ITEM -->


                    <!-- ACCORDION ITEM -->
                    <div class="panel panel-success">
                    <!--  // HEADER -->
                    <div class="panel-heading">
                    <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">2. How do I become a member of the club</a>
                    </h4>
                    </div>
                    <!--  // CONTENT -->
                    <div id="collapseTwo" class="panel-collapse collapse">
                    <div class="panel-body">
                    <hr>
                    <p>Log into the website, click on join the club, then do your registration. After that, pay the sum of five thousand naira( N5000) to the company’s account ( Glochis Club: zenith bank account) . Then text your full name and username to the admin @ 07038728128.</p>
                    </div>
                    </div>
                    </div>
                    <!-- ACCORDION ITEM -->


                    <!-- ACCORDION ITEM -->
                    <div class="panel panel-success">
                    <!--  // HEADER -->
                    <div class="panel-heading">
                    <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">3. Do I have to refer people to the club in order to earn?</a>
                    </h4>
                    </div>
                    <!--  // CONTENT -->
                    <div id="collapseThree" class="panel-collapse collapse">
                    <div class="panel-body">
                    <hr>
                    <p>NO. Glochis Club is NOT a networking business. It is not a ponzi scheme. It is a club of young Nigerians who are destined to create wealth in Nigeria, for Nigerians and by Nigerians. However, it is a moral obligation to share the oppoetunity to every young Nigeria, ESPECIALLY THE RURAL DWELLERS who may not have access to the internet.</p>
                    </div>
                    </div>
                    </div>
                    <!-- ACCORDION ITEM -->


                    <!-- ACCORDION ITEM -->
                    <div class="panel panel-success">
                    <!--  // HEADER -->
                    <div class="panel-heading">
                    <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">4. What do I stand to gain as a member of Glochis Club and when?</a>
                    </h4>
                    </div>
                    <!--  // CONTENT -->
                    <div id="collapseFour" class="panel-collapse collapse">
                    <div class="panel-body">
                    <hr>
                    <p>As a member of Glochis Club, you get to meet with fellow young entrepreneurs, professionals and business giants that will motivate youto work for bright future.</p>
                    <hr>
                    <p>Your membership qualifies you to attend all our seminars, business coaches, workshops, professional trainings etc</p>
                    <hr>
                    <p>On completion of level 3 in our matrix you earn a carrier support of two hundred thousand naira (N200 000) only.</p>
                    <hr>
                    <p>When you start your business Glochis professionals shall offer business advice and mentoring until you become a millionaire</p>
                    
                    </div>
                    </div>
                    </div>
                    <!-- ACCORDION ITEM -->



                </div>


            </div>
        </div>
        
        <br><br>
        <div class="row container">
        </div>
        
        <!-- **************************** FAQ SECTION **************************** -->


    </div>
    </center>
    <!-- PAGE CONTENT -->








    
    <!-- FOOTER -->
    @include ('includes/footer')
    <!-- FOOTER -->


</body>

<!--   Core JS Files   -->
<script src="js/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="js/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

<!-- BINDING ALL JS AND INITIALIZING WEBSITE -->
<script type="text/javascript" src="js/siteInit.js"></script>
<!-- BINDING ALL JS AND INITIALIZING WEBSITE -->

</html>

resources/views/how.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>How it works | Glochis Club | A Glochis African Development Initiative | Empowering our youth</title>

    <!-- SEO CONFIG -->
    @include ('includes/seo')
    <!-- SEO CONFIG -->

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="js/font-awesome-4.7.0/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link href="js/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- <link href="assets/css/now-ui-kit.css" rel="stylesheet" /> -->
    <link href="css/glochis.css" rel="stylesheet" />


</head>


<body>


    <!-- NAVIGATION -->
    @include ('includes/navigation')
    <!-- NAVIGATION -->



    <!-- PAGE CONTENT -->
    <center>
    <div class="" style="min-height:600px;">

        <div class="OtherPagesTop"></div>
        
        <!-- ACTUAL CONTENT -->
        

        <!-- **************************** HOW IT WORKS SECTION **************************** -->
        <div class="row container">
            <div class="col-md-12 Text-to-left">
            <br>
            <h3><strong>How it works</strong></h3>
            <hr />
            </div>
        </div>

        
        <br><br>
        <div class="row container">
            <div class="col-md-3">
            <div class="HOWBOX">
            <div class="BOXERWRAPIcons">1</div>
            Every member is to register through the website, with a one time payment of five thousand naira(N5 000) only.
            </div>
            </div>

            <div class="col-md-4">
            <div class="HOWBOX">
            <div class="BOXERWRAPIcons">2</div>
            After registration, one is expected to pay the sum of N5000 to the company’s account:
                <br><br>
                <strong>Glochis Africa Dev Initiative <br>Zenith Bank: 1015309878</strong>
                <br><br>
                On receipt of the payment alert, the admin. confirms the registration and the member is immediately placed on the club matrix of 5x3
            </div>
            </div>
            
            <div class="col-md-2">
            <div class="HOWBOX">
            <div class="BOXERWRAPIcons">3</div>
            Matrix placement is on the basis of first come first serve.  Matrix growth is from level 1 to level 3. 
            </div>
            </div>
            
            <div class="col-md-3">
            <div class="HOWBOX">
            <div class="BOXERWRAPIcons">4</div>
            On completion of level 3, a member is called an entrepreneur and qualifies for a project fund of two hundred thousand naira (N200 000 ) only, plus a laptop. 
            </div>
            </div>
            
            <!-- 
            <div class="col-md-2">
            <div class="HOWBOX">
            
            </div>
            </div>
            -->

        </div>
        <!-- **************************** HOW IT WORKS SECTION **************************** -->

        <div class="row container">
            <div class="col-md-12">
            
            <div class="Text-to-left">
            <span style="color:#FF2200; font-size:16px;">These benefits are given during our entrepreneurship week.</span>
            <hr />
            <br>
            <h3><strong>Our Method</strong></h3>
            <div class="HOWBOX2">We invite registrations from youths within the age brackets of 9-40years (especially high school students and university undergraduates and graduates).</div>
            <div class="HOWBOX2">We sensitize, educate, inform, motivate,train and empower them into entrepreneurial/technopreneurial skills.</div>
            <div class="HOWBOX2">We guide teenagers and the youths alike to develop their God given talents and skills in order to become successful entrepreneurs and technopreneures and professionals of different fields of endeavors.</div>
            <div class="HOWBOX2">We encourage them to come up with a business plan, technological and innovative ideas related to their area of interest or gifting.</div>
            <div class="HOWBOX2">We provide start up capital for their projects.</div>
            <br><br>
            </div>


            </div>
        </div>
        <!-- ACTUAL CONTENT -->


    </div>
    </center>
    <!-- PAGE CONTENT -->








    
    <!-- FOOTER -->
    @include ('includes/footer')
    <!-- FOOTER -->


</body>

<!--   Core JS Files   -->
<script src="js/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="js/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

<!-- BINDING ALL JS AND INITIALIZING WEBSITE -->
<script type="text/javascript" src="js/siteInit.js"></script>
<!-- BINDING ALL JS AND INITIALIZING WEBSITE -->
</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Glochis Platform - @yield('page')</title>


    <!-- Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ route('home') }}">{{ config('app.name') }}</a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        {{ auth()->user()->name }}<span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu" role="menu">
                        @if(auth()->user()->hasRole('SuperAdmin') || auth()->user()->hasRole('Admin'))
                            <li><a href="{{ url('/5x3admin/dashboard') }}" title="Dashboard"><i class="fa fa-tachometer"></i> Admin Dashboard</a></li>
                        @endif
                        <li><a href="{{ route('home') }}" title="Dashboard"><i class="fa fa-tachometer"></i> Main Dashboard</a></li>

                        <li><a href="{{ route('logout') }}" title="Logout"
                               onclick="event.preventDefault();
                       document.getElementById('logout-form').submit();"><i class="fa fa-btn fa-sign-out"></i>Logout</a>
                        </li>
                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
@yield('content')
</body>

<script type="text/javascript" src="/js/plugins/jquery/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

@yield('footer')
</html>